### ISSUE TITLE
Error with new python generics syntax

### ISSUE THREAD

**Issue by iagocanalejas** [asottile/dead#167]
Hello, first of all, nice projects. I'm having some problems trying to run this with pre-commit. Basically, it's failing when reaching code with the new python syntax for generics.

```
Traceback (most recent call last):
  File "/home/canalejas/.cache/pre-commit/repo05xoyxeg/py_env-python3/bin/dead", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/canalejas/.cache/pre-commit/repo05xoyxeg/py_env-python3/lib/python3.11/site-packages/dead.py", line 319, in main
    tree = _ast(filename)
           ^^^^^^^^^^^^^^
  File "/home/canalejas/.cache/pre-commit/repo05xoyxeg/py_env-python3/lib/python3.11/site-packages/dead.py", line 236, in _ast
    return ast.parse(f.read(), filename=filename)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ast.py", line 50, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/actions/management/helpers/input.py", line 56
    def _input_competition[T: Trophy | Flag](_model: type[T], name: str) -> tuple[T | None, int | None]:
                          ^
SyntaxError: expected '('
```

**Comment by asottile** [comment]
you are using dead from python 3.11 I'm not sure what you expect
